"""SIC division labels shared across observatory builders."""
SIC2 = {
 "01": "Agriculture", "10": "Food manufacturing", "13": "Textiles",
 "16": "Wood products", "18": "Printing", "22": "Rubber and plastics",
 "23": "Non-metallic minerals", "24": "Metals", "25": "Fabricated metal products",
 "26": "Electronics", "27": "Electrical equipment", "28": "Machinery",
 "29": "Motor vehicles", "30": "Other transport equipment", "31": "Furniture",
 "32": "Other manufacturing", "33": "Repair of machinery",
 "35": "Energy", "38": "Waste and recycling", "41": "Construction of buildings",
 "42": "Civil engineering", "43": "Specialised construction",
 "45": "Motor trades", "46": "Wholesale", "47": "Retail",
 "49": "Land transport", "52": "Warehousing", "53": "Postal and courier",
 "55": "Accommodation", "56": "Food and beverage", "58": "Publishing",
 "59": "Film and media", "61": "Telecoms", "62": "IT and software",
 "63": "Information services", "64": "Finance and holding companies",
 "66": "Financial auxiliaries", "68": "Real estate", "69": "Legal and accounting",
 "70": "Head offices and consultancy", "71": "Architecture and engineering",
 "72": "Research", "73": "Advertising", "74": "Other professional",
 "75": "Veterinary", "77": "Rental and leasing", "78": "Employment services",
 "79": "Travel", "80": "Security", "81": "Buildings and landscape services",
 "82": "Office administration", "85": "Education", "86": "Human health",
 "87": "Residential care", "88": "Social work", "90": "Arts",
 "93": "Sport and recreation", "94": "Membership organisations",
 "95": "Repair of goods", "96": "Personal services",
}
